### PR TITLE
Fix modem crashes on LG G2

### PR DESCRIPTION
**Pull request by jonatino**
Fixes modem crashes on LG G2 d803 and other variants.

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by sudosurootdev** [comment]
Was this ever submitted to CM gerrit? No pull requests used.

**Comment by ZdrowyGosciu** [comment]
Yep http://review.cyanogenmod.org/#/c/143159/

**Comment by jonatino** [comment]
@sudosurootdev @ZdrowyGosciu Thanks guys I couldn't find out how gerrit worked so I've just been unpacking/repacking my kernel every time. Much appreciated.

**Pull request closed without merging**
